# coding: utf-8

# flake8: noqa
"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from prometheos_client.models.services_kill_app_request import ServicesKillAppRequest
from prometheos_client.models.services_launch_app200_response import ServicesLaunchApp200Response
from prometheos_client.models.services_launch_app400_response import ServicesLaunchApp400Response
from prometheos_client.models.services_launch_app_request import ServicesLaunchAppRequest
from prometheos_client.models.services_notify_request import ServicesNotifyRequest
from prometheos_client.models.services_open_dialog_request import ServicesOpenDialogRequest
from prometheos_client.models.services_wait_for_event_request import ServicesWaitForEventRequest
