/* tslint:disable */
 
/**
 * PrometheOS API
 * API for AI agent interaction with the PrometheOS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LauncherNotifyRequest
 */
export interface LauncherNotifyRequest {
    /**
     * The notification message to display
     * @type {string}
     * @memberof LauncherNotifyRequest
     */
    'message': string;
    /**
     * Notification engine to use
     * @type {string}
     * @memberof LauncherNotifyRequest
     */
    'type'?: LauncherNotifyRequestTypeEnum;
}

export const LauncherNotifyRequestTypeEnum = {
    radix: 'radix',
    sonner: 'sonner'
} as const;

export type LauncherNotifyRequestTypeEnum = typeof LauncherNotifyRequestTypeEnum[keyof typeof LauncherNotifyRequestTypeEnum];


