/* tslint:disable */
 
/**
 * PrometheOS API
 * API for AI agent interaction with the PrometheOS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LauncherLaunchApp400Response
 */
export interface LauncherLaunchApp400Response {
    /**
     * Operation failed
     * @type {boolean}
     * @memberof LauncherLaunchApp400Response
     */
    'success'?: boolean;
    /**
     * Error message
     * @type {string}
     * @memberof LauncherLaunchApp400Response
     */
    'error'?: string;
}

