/* tslint:disable */
 
/**
 * PrometheOS API
 * API for AI agent interaction with the PrometheOS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServicesWaitForEventRequest
 */
export interface ServicesWaitForEventRequest {
    /**
     * The name of the event to wait for
     * @type {string}
     * @memberof ServicesWaitForEventRequest
     */
    'eventId': string;
    /**
     * Timeout in milliseconds (optional, default is infinite)
     * @type {number}
     * @memberof ServicesWaitForEventRequest
     */
    'timeout'?: number;
}

