/* tslint:disable */
 
/**
 * PrometheOS API
 * API for AI agent interaction with the PrometheOS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServicesOpenDialogRequest
 */
export interface ServicesOpenDialogRequest {
    /**
     * Dialog title
     * @type {string}
     * @memberof ServicesOpenDialogRequest
     */
    'title': string;
    /**
     * Dialog description
     * @type {string}
     * @memberof ServicesOpenDialogRequest
     */
    'description'?: string;
    /**
     * Confirm button label
     * @type {string}
     * @memberof ServicesOpenDialogRequest
     */
    'confirmLabel'?: string;
    /**
     * Cancel button label
     * @type {string}
     * @memberof ServicesOpenDialogRequest
     */
    'cancelLabel'?: string;
}

