/* tslint:disable */
 
/**
 * PrometheOS API
 * API for AI agent interaction with the PrometheOS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServicesLaunchApp200Response
 */
export interface ServicesLaunchApp200Response {
    /**
     * Whether the operation was successful
     * @type {boolean}
     * @memberof ServicesLaunchApp200Response
     */
    'success'?: boolean;
    /**
     * Result data from the operation
     * @type {object}
     * @memberof ServicesLaunchApp200Response
     */
    'data'?: object;
}

