/* tslint:disable */
 
/**
 * PrometheOS API
 * API for AI agent interaction with the PrometheOS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServicesLaunchAppRequest
 */
export interface ServicesLaunchAppRequest {
    /**
     * The ID of the app to launch
     * @type {string}
     * @memberof ServicesLaunchAppRequest
     */
    'appId': string;
}

