// Generated by scripts/generate-unified-client.js
// This file wraps the OpenAPI Generator TypeScript client with our desktop bridge

// Re-export all generated types and APIs
export * from '../prometheos-client-generated';

// Desktop API interface for type safety
interface DesktopBridge {
  api: {
    execute(componentId: string, actionId: string, params?: Record<string, unknown>): Promise<unknown>;
  };
}

// Global desktop API interface
declare global {
  const desktop: DesktopBridge;
}

// Create a custom API client that uses our desktop bridge
class DesktopApiClient {
  async execute(componentId: string, actionId: string, params?: Record<string, unknown>): Promise<unknown> {
    // Use proper type checking without any
    if (typeof globalThis !== 'undefined' && 'desktop' in globalThis) {
      const globalWithDesktop = globalThis as typeof globalThis & { desktop?: DesktopBridge };
      if (globalWithDesktop.desktop?.api?.execute) {
        return globalWithDesktop.desktop.api.execute(componentId, actionId, params);
      }
    }
    throw new Error('Desktop API bridge not available');
  }
}

// Create API instance that uses our desktop bridge
const desktopClient = new DesktopApiClient();

// Consolidated services API using the unified "/api/services" endpoint
export const services = {
  async open(params: { appId: string }) {
    return desktopClient.execute('services', 'open', params);
  },
  async kill(params: { appId: string }) {
    return desktopClient.execute('services', 'kill', params);
  },
  async restart(params: { appId: string }) {
    return desktopClient.execute('services', 'restart', params);
  },
  async notify(params: { message: string; type: 'radix' | 'sonner' }) {
    return desktopClient.execute('services', 'notify', params);
  },
  async openDialog(params: { title: string; description: string; confirmLabel: string; cancelLabel: string }) {
    return desktopClient.execute('services', 'openDialog', params);
  },
  async waitForEvent(params: { eventId: string; timeout: number }) {
    return desktopClient.execute('services', 'waitForEvent', params);
  },
  async listEvents(params: Record<string, never> = {}) {
    return desktopClient.execute('services', 'listEvents', params);
  }
};

// Export low-level API access
export const api = {
  execute: desktopClient.execute.bind(desktopClient)
};

// Default export
export default {
  services,
  api
};
