# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.models.services_open_request import ServicesOpenRequest

class TestServicesOpenRequest(unittest.TestCase):
    """ServicesOpenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicesOpenRequest:
        """Test ServicesOpenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicesOpenRequest`
        """
        model = ServicesOpenRequest()
        if include_optional:
            return ServicesOpenRequest(
                app_id = ''
            )
        else:
            return ServicesOpenRequest(
                app_id = '',
        )
        """

    def testServicesOpenRequest(self):
        """Test ServicesOpenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
