# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.api.system_api import SystemApi


class TestSystemApi(unittest.IsolatedAsyncioTestCase):
    """SystemApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_dialog_open_dialog(self) -> None:
        """Test case for dialog_open_dialog

        Open Dialog
        """
        pass

    async def test_event_list_events(self) -> None:
        """Test case for event_list_events

        List Events
        """
        pass

    async def test_launcher_kill_app(self) -> None:
        """Test case for launcher_kill_app

        Kill App
        """
        pass

    async def test_launcher_launch_app(self) -> None:
        """Test case for launcher_launch_app

        Launch App
        """
        pass

    async def test_launcher_notify(self) -> None:
        """Test case for launcher_notify

        Notify
        """
        pass

    async def test_on_event_wait_for_event(self) -> None:
        """Test case for on_event_wait_for_event

        Wait For Event
        """
        pass


if __name__ == '__main__':
    unittest.main()
