# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.models.launcher_launch_app400_response import LauncherLaunchApp400Response

class TestLauncherLaunchApp400Response(unittest.TestCase):
    """LauncherLaunchApp400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LauncherLaunchApp400Response:
        """Test LauncherLaunchApp400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LauncherLaunchApp400Response`
        """
        model = LauncherLaunchApp400Response()
        if include_optional:
            return LauncherLaunchApp400Response(
                success = False,
                error = ''
            )
        else:
            return LauncherLaunchApp400Response(
        )
        """

    def testLauncherLaunchApp400Response(self):
        """Test LauncherLaunchApp400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
