# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.models.launcher_notify_request import LauncherNotifyRequest

class TestLauncherNotifyRequest(unittest.TestCase):
    """LauncherNotifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LauncherNotifyRequest:
        """Test LauncherNotifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LauncherNotifyRequest`
        """
        model = LauncherNotifyRequest()
        if include_optional:
            return LauncherNotifyRequest(
                message = '',
                type = 'radix'
            )
        else:
            return LauncherNotifyRequest(
                message = '',
        )
        """

    def testLauncherNotifyRequest(self):
        """Test LauncherNotifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
