# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.models.services_open400_response import ServicesOpen400Response

class TestServicesOpen400Response(unittest.TestCase):
    """ServicesOpen400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicesOpen400Response:
        """Test ServicesOpen400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicesOpen400Response`
        """
        model = ServicesOpen400Response()
        if include_optional:
            return ServicesOpen400Response(
                success = False,
                error = ''
            )
        else:
            return ServicesOpen400Response(
        )
        """

    def testServicesOpen400Response(self):
        """Test ServicesOpen400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
