# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.models.dialog_open_dialog_request import DialogOpenDialogRequest

class TestDialogOpenDialogRequest(unittest.TestCase):
    """DialogOpenDialogRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DialogOpenDialogRequest:
        """Test DialogOpenDialogRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DialogOpenDialogRequest`
        """
        model = DialogOpenDialogRequest()
        if include_optional:
            return DialogOpenDialogRequest(
                title = '',
                description = '',
                confirm_label = '',
                cancel_label = ''
            )
        else:
            return DialogOpenDialogRequest(
                title = '',
        )
        """

    def testDialogOpenDialogRequest(self):
        """Test DialogOpenDialogRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
