# coding: utf-8

"""
    PrometheOS API

    API for AI agent interaction with the PrometheOS

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prometheos_client.models.on_event_wait_for_event_request import OnEventWaitForEventRequest

class TestOnEventWaitForEventRequest(unittest.TestCase):
    """OnEventWaitForEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnEventWaitForEventRequest:
        """Test OnEventWaitForEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnEventWaitForEventRequest`
        """
        model = OnEventWaitForEventRequest()
        if include_optional:
            return OnEventWaitForEventRequest(
                event_id = '',
                timeout = 1.337
            )
        else:
            return OnEventWaitForEventRequest(
                event_id = '',
        )
        """

    def testOnEventWaitForEventRequest(self):
        """Test OnEventWaitForEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
